export const CLAUDE_CLI_RUNNER = Symbol('CLAUDE_CLI_RUNNER');
export const GIT_PUBLICATION_CLIENT = Symbol('GIT_PUBLICATION_CLIENT');
export const GITHUB_PULL_REQUESTS_GATEWAY = Symbol(
  'GITHUB_PULL_REQUESTS_GATEWAY',
);
